// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1j8HndHBLSwMFOXbel1VGCLiSi_bvaOE',
    appId: '1:330648345478:web:4a94843fa4ae15e7486a07',
    messagingSenderId: '330648345478',
    projectId: 'rotaract-584b8',
    authDomain: 'rotaract-584b8.firebaseapp.com',
    storageBucket: 'rotaract-584b8.appspot.com',
    measurementId: 'G-D8BPQVJHKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVBeq9U3OjtI9vpNTlyp4g3_VJY4rJxa8',
    appId: '1:330648345478:android:1e44b76945f59f38486a07',
    messagingSenderId: '330648345478',
    projectId: 'rotaract-584b8',
    storageBucket: 'rotaract-584b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6A_GJJ78o-SvwRLIAaS5zUXVfanS25iE',
    appId: '1:330648345478:ios:67a19a5dd3f79ae9486a07',
    messagingSenderId: '330648345478',
    projectId: 'rotaract-584b8',
    storageBucket: 'rotaract-584b8.appspot.com',
    iosBundleId: 'elastictech.biz.rotaract',
  );
}
